load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
cc_library(
    name = "timestamp_parser_lib",
    srcs = ["timestamp_parser.c"],
    hdrs = ["timestamp_parser.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)