name: PR Tests

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:

  build_ci_image:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build CI Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/bazel-ci:${{ github.sha }}
          docker build -f Dockerfile.ci -t $IMAGE .
          docker push $IMAGE

  run_tests:
    needs: build_ci_image
    runs-on: self-hosted

    container:
      image: ghcr.io/${{ github.repository }}/bazel-ci:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bazel tests
        run: |
          bazel test //test:test_dummy_logger
