name: PR Tests

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:

  build_ci_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build CI Docker image
        run: |
          echo "Test"
